#!/usr/bin/env node
import { compileFromFile } from "json-schema-to-typescript";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

export async function codegenTypes(schemasDir) {
  const outDir = path.join(ROOT, "lib", "opentide", "generated");
  fs.mkdirSync(outDir, { recursive: true });

  if (!fs.existsSync(schemasDir)) {
    console.warn(`Schemas dir not found: ${schemasDir} — skipping codegen`);
    return;
  }

  const schemas = fs
    .readdirSync(schemasDir)
    .filter((f) => f.endsWith(".schema.json"));

  const parts = [
    "/* eslint-disable */",
    "/* auto-generated by scripts/codegen-types.mjs — do not edit */",
    "",
  ];

  for (const schemaFile of schemas) {
    try {
      const ts = await compileFromFile(path.join(schemasDir, schemaFile), {
        bannerComment: "",
        unreachableDefinitions: true,
      });
      parts.push(ts);
    } catch (err) {
      console.warn(
        `Skipping schema ${schemaFile}:`,
        err instanceof Error ? err.message : err,
      );
    }
  }

  fs.writeFileSync(path.join(outDir, "schemas.ts"), parts.join("\n"));
  console.log(
    `Generated ${schemas.length} schema types → lib/opentide/generated/schemas.ts`,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const schemasDir =
    process.argv[2] ?? path.resolve(ROOT, "../library/.opentide/schemas");
  codegenTypes(schemasDir).catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
